### ISSUE TITLE
Take a look at gnirehtet

### ISSUE THREAD

**Issue by a5m0** [robinpaulson/SimpleRT#24]
I was wondering if you'd taken a look at https://github.com/Genymobile/gnirehtet and if you had an opinion of which project had better implementation/features. Just some friendly cross-pollination, thanks!

**Comment by vvviperrr** [comment]
Hi.
Using adb was my first thought, when i started working on SimpleRT. But there already were some implementations (in google play), and they sucks. Most of all, users got issues with adb itself. It should be properly configured, enabled in phone, etc. The main issue - adb reverse command works only in 21 api and higher, while simplert works on 14 api (the first api where vpn service shows up). Second, relay method supports only tcp/udp, when simplert works as virtual interface, u can use any type of traffic. And i suppose, simplert has a higher data transfer rate (in my tests - about 20-30 mbytes per sec), as ip packets transferred via pure usb bulk transfer and injects into system tcp/ip stack. And of course, as SimpleRT implemented on C, u can use it literally anywhere. For instance, i built it for tplink mr3020 router (with openwrt), and got kind of "usb wifi modem" for android :)

So, in my opinion, gnirehtet has only one advantage over simplert - windows support. Now I'm working on windows port, but it is really pain in the ass (im not windows guy). But its quite possible.

**Comment by Zero3K** [comment]
Is the Windows port ready yet?

**Comment by vvviperrr** [comment]
nope, only compile issues fixed. libusb is not fully supported on windows, thats the main problem. still working on it.

**Comment by Zero3K** [comment]
Try the version of libusb located at http://libusb.info/.

**Comment by Zero3K** [comment]
Will it work or not?

**Comment by vvviperrr** [comment]
i already use this version. in short - windows version of simplert need to be heavy rewritten. now im trying to reduce this work.

**Comment by Zero3K** [comment]
How much longer will it take?

**Comment by vvviperrr** [comment]
windows version release? don't have any schedule, as windows is not my primary area of interests. maybe 2-3 months, maybe more.

**Comment by Zero3K** [comment]
Unless someone decides to help you with making a port for it.

**Comment by casper** [comment]
Here's another vote for a Windows version.

I just went through 5 different reverse tethering apps and none of them are simple nor work properly without root access. The closest solution for Windows was using OpenVPN, but it's an extremely complex setup, and it still doesn't work very well. This one seems to be the best one so far. Just needs some Windows love. 

Did you consider running under Cygwin? Perhaps using that would make the whole setup easier to port.

**Comment by Biswa96** [comment]
@casper How did you do that with OpenVPN? Can you elaborate that process? I shall try that.

**Comment by casper** [comment]
@Biswa96 It was a while ago I did it, but I think it this is the tutorial I was using for that:   
http://salutepc.altervista.org/usb-reverse-tethering-no-root-no-adb-android-all-versions-windows-10.html

Also check out gnirehtet, it might actually be the simplest tool of them all for Windows:  
https://medium.com/genymobile/gnirehtet-reverse-tethering-android-2afacdbdaec7

**Comment by Biswa96** [comment]
@casper I'm learning programming in C. So I can easily understand simpleRT and I like to stay more near to hardware.

Gnirehtet uses some sort of library to maintain the asynchronous mechanism to avoid the root permission. Also it has some limitations like TCP and UDP only and ADB dependency.

**Comment by Biswa96** [comment]
Is it possible to make the APK file for Android in Eclipse? I'm bit unfamiliar with Android Studio and gradle packaging.

**Comment by robinpaulson** [comment]
I'm going to close this issue, other than "it runs on Windows", I don't think there's any particular thing we can borrow from gnirehtet. There is a Windows client issue open at #50 .
