### ISSUE TITLE
Issue with it and Lubuntu

### ISSUE THREAD

**Issue by Zero3K** [robinpaulson/SimpleRT#32]
When using the debug output parameter, letting the log that's display grow and pressing CTRL+C, it froze the OS on me.

**Comment by vvviperrr** [comment]
you should use debug option only for tethering problem resolving (collect logs, etc). its not working mode.

**Comment by Zero3K** [comment]
That's what I was using it for. It just froze on me again.

**Comment by vvviperrr** [comment]
if u try to heavy use network (download app, watch video, etc) when debug option enabled - A LOT of logs will be generated. debug option is used when simplert not working AT ALL. no key sign in toolbar, no internet in chrome, nothing.

**Comment by Zero3K** [comment]
Not for figuring out why programs don't work most of the time?

**Comment by vvviperrr** [comment]
on my device everything works just fine. you first who complain. what device do you have?

**Comment by Zero3K** [comment]
I have an Acer Iconia One 8.

**Comment by Zero3K** [comment]
I hope my issues are fixable.

**Comment by robinpaulson** [comment]
HI @Zero3K could you go into a little more detail? vvviperrr makes a valid point that running all the time in debug mode will generate a lot of unnecessary data.

Is there any particular bug you're trying to fix, other than debug mode overflowing and causing problems?
