### ISSUE TITLE
Problems assigning routes; manual intervention required

### ISSUE THREAD

**Issue by AndySardina** [robinpaulson/SimpleRT#36]
Hello,

 I've been using SimpleRT apps, but on my phone, a Samsung Galaxy J1 (SM-J100H) running Android 4.4.4, I have to run manually from a terminal emulator:
```bash
   $ su
   $ ip route add default via 10.1.1.1
```
in order to be able to connect the phone to the PC network. It seems to be a problem with Android 4.4 because in a Nexus 5 running Android 7, the same default route created by SimpleRT app works fine.

**Comment by robinpaulson** [comment]
Hi @AndySardina I realise this is a very old bug, where are you at with it?

**Comment by AndySardina** [comment]
Hi there!
 You can close this issue.
